### ISSUE TITLE
Failed to list *v1alpha1.CSIDriver: csidrivers.csi.storage.k8s.io is forbidden

### ISSUE THREAD

**Issue by shix16** [LINBIT/linstor-csi#1]
Hi there,

Linstor-CSI works with the latest version k8s (1.13.3),  we can use dynamic provision drbd  sds volume in k8s cluster and mout/unmount them to specific pods. However, we still continually got error message from kubelet log as below, "master03" is my one of k8s node name, is it permission issue?

kubelet[1410374]: E0204 14:15:56.104528 1410374 reflector.go:134] k8s.io/csi-api/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.CSIDriver: csidrivers.csi.storage.k8s.io is forbidden: User "system:node:master03" cannot list resource "csidrivers" in API group "csi.storage.k8s.io" at the cluster scope.

Regards,
Tony

**Comment by haySwim** [comment]
What feature gates do you have enabled on your kubelets and your kube-api server? For 1.13 you'll need to turn on `CSIDriverRegistry` and `CSINodeInfo`

**Comment by shix16** [comment]
Yes, I did. Enabled the both flags for kubelet and kube-api. 
However, I got following information "Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag" from kubelet log, is it means that "--feature-gates" will not work?

**Comment by shix16** [comment]
They are enabled.
```
 ps aux | grep feature\-gates
root     1923945  6.2  0.7 1068340 122948 ?      Ssl  11:00  10:07 /usr/bin/kubelet --feature-gates=CSINodeInfo=true,CSIDriverRegistry=true --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=cgroupfs --network-plugin=cni --node-status-update-frequency=4s
root     1925189  3.7  2.3 584532 388888 ?       Ssl  11:02   6:06 kube-apiserver --authorization-mode=Node,RBAC --advertise-address=192.168.1.253 --allow-privileged=true --client-ca-file=/etc/kubernetes/pki/ca.crt --enable-admission-plugins=NodeRestriction --enable-bootstrap-token-auth=true --etcd-servers=http://192.168.1.251:2379,http://192.168.1.252:2379,http://192.168.1.253:2379 --insecure-port=0 --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/etc/kubernetes/pki/front-proxy-client.crt --proxy-client-key-file=/etc/kubernetes/pki/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-key-file=/etc/kubernetes/pki/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/etc/kubernetes/pki/apiserver.crt --tls-private-key-file=/etc/kubernetes/pki/apiserver.key --feature-gates=CSINodeInfo=true,CSIDriverRegistry=true
```

**Comment by haySwim** [comment]
This might be a issue with [node restriction](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#noderestriction), but I haven't really messed with that myself, it's the only thing that comes to mind looking at your kube-api flags.

Also, double checking that all kubelets have their feature-gates enabled could be useful, just for paranoia's sake.

**Comment by haySwim** [comment]
I'm going to go ahead and close this out.

/wontfix
