### ISSUE TITLE
Incorrectly named driver

### ISSUE THREAD

**Issue by saad-ali** [LINBIT/linstor-csi#11]
Per the [CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#getplugininfo) the name of a CSI driver must conform to the following requirements:

```
The name MUST follow domain name notation format (https://tools.ietf.org/html/rfc1035#section-2.3.1).

It SHOULD include the plugin's host company name and the plugin name, to minimize the possibility of collisions.

It MUST be 63 characters or less, beginning and ending with an alphanumeric character ([a-z0-9A-Z]) with dashes (-), dots (.), and alphanumerics between.

This field is REQUIRED.
```

While CSI 0.x required reverse domain notation, [CSI 1.0](https://github.com/container-storage-interface/spec/releases/tag/v1.0.0) dropped the "reverse" part of the requirement. The expectation is that the name will be normal (forward) domain notation.

So for CSI 1.0, instead of `io.drbd.linstor-csi` the driver name should be `linstor.csi.drbd.io` (I would do `.csi.` instead of `-csi.`, but that's just my personal opinion).

**Comment by haySwim** [comment]
Thanks for that. We might use this opportunity to switch up the name a bit, so I'll need to let management decide before I push these changes out.

**Comment by haySwim** [comment]
@saad-ali is it acceptable to allow users to change the driver name?

Right now, we use the driver name to check to see if the plugin created existing volumes, so I'm trying to determine the least bad way to ensure backwards compat.

**Comment by saad-ali** [comment]
Backwards compatibility will definitely be an issue. If you change the name the new driver will not pick up volumes from the old driver.

To minimize interruption, you would have to deploy old and new driver concurrently (handling old and new name volumes respectively). Then you'd have to go in and replace the `PV.spec.CSIVolumeSource.Driver` with the new name. I forget if that field is even allowed to mutate. If it is not, then replacement becomes even more tricky -- you have to create a new PV object and swap out the old one.

Ultimately it's up to you, the forward/reverse domain notation is not enforced anywhere. So you could continue to use the reverse name without issue if backwards compat is too big of a headache.

**Comment by kvaps** [comment]
I can answer.
You can't change `.spec.csi.driver` and `.spec.csi.volume.volumeAttributes.storage.kubernetes.io/csiProvisionerIdentity` fields without recreating PV.

I can tell even more, I have success for updating volumes metadata, eg flexvolumes to csi, and old csi to new format (after https://github.com/LINBIT/linstor-csi/pull/3)
You can't simple remove existing PV, because it will entail deleting resources in linstor. For avoid this, you have to do the next steps:
- Stop linstor-csi-provisioner (just in case)
- Remove `.metadata.finalizers` from PV volumes
- Remove the volumes itself
- Remove `.metadata.finalizers` again.

After that all PV's metadata will be removed from the cluster, and PVC will obtain `Lost` state.

- Now you can create new volumes with the same `.spec.claimRef` field, they will be bound with existing PVC's
- Then deploy new linstor-csi-provisioner.

This procedure can be done online, without stopping the pods.

I wrote little script for generate commands to update PVs for myself:
https://github.com/kvaps/linstor-csi-migrator

Cheers

**Comment by haySwim** [comment]
Okay, swapping out the PVs or using concurrent drivers doesn't sound especially tragic and my boss wants to change the name anyhow. So I'll say that's the way forward.

**Comment by kvaps** [comment]
Just found one problem with that, if you update PV metadata online without stopping the running pods. And then try to terminate them, pods will hung forever trying to unmount volume from the new driver's path, so you have to do unmount operation from old driver's place manually.
Newly created pod with updated metadata will work fine.

**Comment by saad-ali** [comment]
Ah yes, good point. Only way to handle that more gracefully would be to make the new driver handle the old driver's name for some time. Or just require termination.

**Comment by haySwim** [comment]
I don't think requiring termination is going to be too big of an issue. Here's hoping.

**Comment by haySwim** [comment]
@kvaps you'll also need to update the props on the resource definitions as well, like you did for the IDs

**Comment by kvaps** [comment]
@haySwim shoud I also update `.spec.csi.volumeAttributes."storage.kubernetes.io/csiProvisionerIdentity"` for PVs?

eg. from `1551278453900-8081-io.drbd.linstor-csi` to `1551278453900-8081-linstor.csi.linbit.com`

**Comment by kvaps** [comment]
> Just found one problem with that, if you update PV metadata online without stopping the running pods and then try to terminate them. These pods will hung forever trying to unmount volume from the new driver's path, so you have to go on the node and do unmount operation from old driver's path manually.
> After that pod will be successfully terminated and the newly created pod will work totally fine.

It seems that only old flexvolumes is problematic, CSI volumes always have union path
```
/var/lib/kubelet/pods/<pod_id>/volumes/kubernetes.io~csi
```

**Comment by kvaps** [comment]
BTW, I've successfully upgraded all my volumes to use new driver name using [https://github.com/kvaps/linstor-csi-migrator](https://github.com/kvaps/linstor-csi-migrator)

Termination for existing pods is working fine after running this command on every host:

```bash
sed -i 's/io.drbd.linstor-csi/linstor.csi.linbit.com/g' `find /var/lib/kubelet/pods/ -mindepth 5 -maxdepth 5 -name vol_data.json`
```
