### ISSUE TITLE
Invalid JSON in Aux/csi-volume-annotations property breaks other volumes provisioning

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-csi#13]
I'm not sure that it is expected behavior, but If any resource ddefinition in your cluster have `Aux/csi-volume-annotations` property with invalid JSON for some reason, then provisioning for any other volume will fail with the `failed to unmarshal annotations for ResDef` error.

**Comment by haySwim** [comment]
It's possible this will be incidentally resolved soon, but that's not the goal of the forthcoming change.

This is essentially a problem at the data layer, unless the plugin is writing out invalid JSON.
