### ISSUE TITLE
example linstor-csi.yaml is not compatible with Kubernetes 1.14

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-csi#6]
After upgrade to `v1.14` csi driver is not working.
Any attempt to attach the volume ends up with the error `err=no volume plugin matched`.
I guess problem was caused by moving `CSIDriver` from `csi.storage.k8s.io/v1alpha1` to `storage.k8s.io/v1beta1`

`csi-cluster-driver-registrar` log says:

```
I0326 16:18:08.628649       1 k8s_register.go:69] CSIDriver CRD already had been registered
```

but `kubectl  get csidrivers.csi.storage.k8s.io` returns nothing.

csi-cluster-driver-registrar uses `quay.io/k8scsi/csi-node-driver-registrar:v1.0.2` image

**Comment by haySwim** [comment]
Yeah, I think you might be right with CSINodeInfo moving to beta.

csi-cluster-driver-registrar is at the latest version and it's `quay.io/k8scsi/csi-cluster-driver-registrar:v1.0.1` not `quay.io/k8scsi/csi-node-driver-registrar:v1.0.2`

Looks like this is the issue https://github.com/kubernetes/kubernetes/pull/74283

I don't have a 1.14 cluster up at the moment, but it might be as simple as changing https://github.com/LINBIT/linstor-csi/blob/master/examples/k8s/deploy/linstor-csi.yaml#L32 that to `v1beta1`

**Comment by kvaps** [comment]
I don't think that we need any CRD since now.
* `csidrivers.storage.k8s.io` was exsiting after upgrade to `v1.14` from beginning.
* What about `csinodeinfos.csi.storage.k8s.io` it was problably moved to `csinodes.storage.k8s.io` (it is existing from beginning too)

* > csi-cluster-driver-registrar is at the latest version

    I've tested all four versions with same result:
    ```
            "v1.0.1", # 2018-12-10T19:53:08.651780702Z
            "v1.0.2", # 2018-12-27T23:22:18.963300422Z
            "canary", # 2019-01-11T23:46:26.53118884Z
            "v1.0-canary" # 2019-02-07T01:46:25.442209631Z
    ```
* Of course I was updated CusterRole before to `storage.k8s.io`
https://github.com/LINBIT/linstor-csi/blob/0efd7e8cfa9c61f0dd94c3e30f44a14bfc935017/examples/k8s/deploy/linstor-csi.yaml#L203
replaced

**Comment by kvaps** [comment]
Ok, I have success with the `quay.io/k8scsi/csi-cluster-driver-registrar:tmp-test-1.14` version from `2019-03-05T22:03:49.322820892Z`. Now driver registered in the right place in the `csidrivers.storage.k8s.io`

**Comment by haySwim** [comment]
Alight, that's pretty nice and easy. Since 1.14 is less than 24 hours old at this point, I'm going to wait until a more stable release of the csi-cluster-driver-registrar comes out before updating the example deployments.

**Comment by kvaps** [comment]
Yep, csi-attacher now is also not working :)

**Comment by kvaps** [comment]
Hi @haySwim, sorry for the noize, I was little confused in my cluster, currently I can say that current example `linstor-csi.yaml` is fully compatible with new  Kubernetes v1.14.
