### ISSUE TITLE
Helm chart to deploy on GKE

### ISSUE THREAD

**Issue by sorleone** [LINBIT/linstor-csi#63]
Is there an Helm chart to deploy Linstron on Google Kubernetes Engine?

**Comment by rck** [comment]
Puh, lots of transitions to come, I try to make that as clear as possible:
- `LINBIT/linstor-csi` will become `piraeusdatastore/piraeus-csi`
- think of that like Redhat vs. Centos
- We currently work on a k8s operator. this will be/is `piraeusdatastore/piraeus-operator`
- There will be a helm chart for the piraeus-operator
- So if you want to use FLOSS, you have to check out `piraeusdatatstore`

If you need certified containers and support: There will be LINBIT equivalents (e.g., linstor-operator and a helm chart for that), but these will require containers from a registry only our customers have access to.

tl;tr: most likely you want to check out "piraeusdatastore" and what happens there

**Comment by sorleone** [comment]
@rck Thank you for your reply. What is FLOSS? `piraeusdatastore/piraeus-csi` doesn't exists, only <https://github.com/piraeusdatastore/linstor-csi> does. Where is `piraeusdatatstore`? The only things I could find are these:

https://github.com/piraeusdatastore/linstor-csi
https://github.com/piraeusdatastore/piraeus
https://github.com/piraeusdatastore/piraeus-operator

What should I use between them, in order to have ReadWriteMany PVCs that can be replicated like a RAID 1?

**Comment by rck** [comment]
Both are FLOSS. There is a difference on which base images the components are based and not all of the images generated from the LINBIT/ namespace might be publicly available (some might be LINBIT customers only). We as LINBIT obviously do not support the Piraeus images (it is a best effort github FLOSS project to us), but we do provide commercial support for the LINBIT components. Think of it as RHEL vs. Centos.

piraeusdatastore is the right place. That is what we currently have. It is still a young project.

ReadWriteMany is being worked on. "soon".
