### ISSUE TITLE
Not able to use satellite nodes outside of Kubernetes cluster

### ISSUE THREAD

**Issue by BadriL** [LINBIT/linstor-csi#64]
May be this is not an issue and that I'm not aware of how to configure but then I started with the setup of K8s cluster with its own nodes and the Linstor cluster completely outside of it, with its own controller and two satellite nodes (6 Linux servers totally). With that, when PV is provisioned, it has nodeaffinity set so that pods could be created only in linbit.com/hostname=&lt;satellite&gt;. This is a problem since K8s cluster nodes are completely different and no pods would get scheduled. Then, I modified the setup to run Linstor converged - that is, I have a separate controller server but then use the K8s minion nodes as Linstor controllers. So, four servers in all - K8s master, Linstor controller, and two K8s minion/satellites. Now, the problem is, when a minion/satellite goes down, K8s is not able to schedule the pod. ~~because of the classic "Multi-Attach" error, since I use AWS EBS volumes for the storage pool. Eventually, it worked with EBS volume getting detached.~~ The issue I'd like to raise is the lack of ability to run the linstor cluster completely outside so that regardless of the node where the K8s pod is scheduled, the storage can be accessed. Again, this might not be an issue. Just that, I don't know how to configure. If that's the case, please feel free to close this issue. If you can provide me some pointers, it'd be greatly appreciated.

UPDATE: I mistook the multi-attach for EBS issue. Looks like it is not. Sorry about that.

**Comment by JoelColledge** [comment]
Hi @BadriL 

I haven't understood your intention entirely, but it looks like the core of your question is

> The issue I'd like to raise is the lack of ability to run the linstor cluster completely outside so that regardless of the node where the K8s pod is scheduled, the storage can be accessed.

It should be possible to run the controller outside of the k8s cluster. It should also be possible to have storage servers with satellies outside of the k8s cluster. However you still need satellites on each node which should be able to access the data. They are necessary for setting up access to the data using DRBD.

**Comment by BadriL** [comment]
Thanks Joel for the reply. My apologies for not making my question clearer. Anyways, you got it correctly. Because of the nodeaffinity restriction in the PV, I tried to make the satellite nodes and the minion one and the same but ideally I want Linstor cluster to be completely outside of k8s cluster. I believe the key point in your reply is this.

> However you still need satellites on each node which should be able to access the data.

Can you please give me some info, if possible. It is clear I need to install `linstor-satellite` in each of the K8s nodes. In addition to this, do I need to do anything else? Do I need to register the K8s nodes with Linstor using `linstor node create <nodename> <IP>`?

**Comment by JoelColledge** [comment]
> It is clear I need to install linstor-satellite in each of the K8s nodes. In addition to this, do I need to do anything else? Do I need to register the K8s nodes with Linstor using linstor node create <nodename> <IP>?

This looks correct to me. Install DRBD and `linstor-satellite`, then do `linstor node create ...`.

The alternative would be to put all your nodes in your kubernetes cluster and manage linstor with https://github.com/piraeusdatastore/piraeus-operator

**Comment by BadriL** [comment]
Fantastic. Thanks a lot for your help. I'll explore the Piraeus Operator tomorrow.
